spring.application.name=miniRTB

spring.datasource.url=jdbc:postgresql://ep-mute-rice-atx6cc2m-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_lJY9KW6sepQC&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lJY9KW6sepQC

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080